dnnlib: Running train.train() on localhost...

Warning: No validation images found in /Users/prachit/self/[0]Working/OCT/noise2noise/results/datasets/kodak
Creating a dummy validation set from the first training image
ERROR: No images found for validation!
Setting up dataset source from /Users/prachit/self/[0]Working/OCT/noise2noise/datasets/imagenet_val_raw.tfrecords
Traceback (most recent call last):
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/config.py", line 219, in <module>
    args.func(args)
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/config.py", line 152, in train
    dnnlib.submission.submit.submit_run(submit_config, **train_config)
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/dnnlib/submission/submit.py", line 300, in submit_run
    run_wrapper(submit_config)
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/dnnlib/submission/submit.py", line 243, in run_wrapper
    util.call_func_by_name(func_name=submit_config.run_func_name, submit_config=submit_config, **submit_config.run_func_kwargs)
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/dnnlib/util.py", line 232, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/train.py", line 97, in train
    dataset = create_dataset(train_tfrecords, minibatch_size,
  File "/Users/prachit/self/[0]Working/OCT/noise2noise/dataset.py", line 65, in create_dataset
    dset = dset.map(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2299, in map
    return map_op._map_v2(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py", line 265, in __init__
    self._function = fn_factory()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1251, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1221, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 696, in _initialize
    self._concrete_variable_creation_fn = tracing_compilation.trace_function(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 178, in trace_function
    concrete_function = _maybe_define_function(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 283, in _maybe_define_function
    concrete_function = _create_concrete_function(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 310, in _create_concrete_function
    traced_func_graph = func_graph_module.func_graph_from_py_func(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1059, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 599, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py", line 231, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py", line 161, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 693, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 690, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/var/folders/wf/l9dtgxnd7ng4lhszcp8g5g1m0000gn/T/__autograph_generated_filehlj53bi8.py", line 6, in <lambda>
    tf__lam = lambda x: ag__.with_function_scope(lambda lscope: ag__.converted_call(random_crop_noised_clean, (x, add_noise), None, lscope), 'lscope', ag__.STD)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/core/function_wrappers.py", line 113, in with_function_scope
    return thunk(scope)
  File "/var/folders/wf/l9dtgxnd7ng4lhszcp8g5g1m0000gn/T/__autograph_generated_filehlj53bi8.py", line 6, in <lambda>
    tf__lam = lambda x: ag__.with_function_scope(lambda lscope: ag__.converted_call(random_crop_noised_clean, (x, add_noise), None, lscope), 'lscope', ag__.STD)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/var/folders/wf/l9dtgxnd7ng4lhszcp8g5g1m0000gn/T/__autograph_generated_file04h3t7gj.py", line 18, in tf__random_crop_noised_clean
    retval_ = (ag__.converted_call(ag__.ld(add_noise), (ag__.ld(cropped),), None, fscope), ag__.converted_call(ag__.ld(add_noise), (ag__.ld(cropped),), None, fscope), ag__.ld(cropped))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/n2n/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/var/folders/wf/l9dtgxnd7ng4lhszcp8g5g1m0000gn/T/__autograph_generated_filezh8scx5u.py", line 12, in tf__add_train_noise_tf
    rng_stddev = ag__.converted_call(ag__.ld(tf).random_uniform, (), dict(shape=[1, 1, 1], minval=ag__.ld(minval) / 255.0, maxval=ag__.ld(maxval) / 255.0), fscope)
AttributeError: in user code:

    File "/Users/prachit/self/[0]Working/OCT/noise2noise/dataset.py", line 66, in None  *
        lambda x: random_crop_noised_clean(x, add_noise)
    File "/Users/prachit/self/[0]Working/OCT/noise2noise/dataset.py", line 52, in random_crop_noised_clean  *
        return (add_noise(cropped), add_noise(cropped), cropped)
    File "/Users/prachit/self/[0]Working/OCT/noise2noise/train.py", line 31, in add_train_noise_tf  *
        rng_stddev = tf.random_uniform(shape=[1, 1, 1], minval=minval/255.0, maxval=maxval/255.0)

    AttributeError: module 'tensorflow' has no attribute 'random_uniform'

